//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCPharmacyAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int MedicineId { get; set; }
        public string Full_Name { get; set; }
        public string Brand { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Expiry_Date { get; set; }
        public string Notes { get; set; }
    }
}
